[package]
name = "webServer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.6"
actix-web = "4.5.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
dotenv = "0.15.0"
