use crate::{views::recommendations, middleware};
use actix_web::web::{get, post, scope, ServiceConfig};

pub fn config(cfg: &mut ServiceConfig) {
    cfg.service(
        scope("/save")
        .wrap(middleware::authentication)
        .route(
            "/audionotes",
            post().to(views::reader::notes::save::audionote),
        )
        .route(
            "/highlights",
            post().to(views::reader::notes::save::highlight),
        )
        .route(
            "/quotes",
            post().to(views::reader::notes::save::audionote),
        )
        .route(
            "/notes",
            post().to(views::reader::notes::save::text),
        )
    )
    .service(
        scope("/load")
        .wrap(middleware::authentication)
        .route(
            "/audionotes",
            post().to(views::reader::notes::save::audionote),
        )
        .route(
            "/highlights",
            post().to(views::reader::notes::save::highlight),
        )
        .route(
            "/quotes",
            post().to(views::reader::notes::save::audionote),
        )
        .route(
            "/notes",
            post().to(views::reader::notes::save::text),
        )
    )
    .service(
        scope("/summary")
        .wrap(middleware::authentication)
        .route(
            "/download",
            post().to(views::reader::summary::download)
        )
        .route(
            "/cache",
            post().to(views::reader::summary::cache)
        )
    )
    .service(
        scope("/ruler")
        .wrap(middleware::authentication)
        .route(
            "/get-status",
            post().to(views::reader::place::ruler)
        )
        .route(
            "/toggle-account",
            post().to(views::reader::place::ruler)
        )   
        .route(
            "/toggle-device-type",
            post().to(views::reader::place::ruler)
        )
        .route(
            "/toggle-device",
            post().to(views::reader::place::ruler)
        )
    )
    .service(
        scope("location")
        .wrap(middleware::authentication)
        .route(
            "get-place",
            get().to(views::reader::place)
        )
        .route(
            "set-place",
            post().to(views::reader::place)
        )
    )
    .service(
        scope("chapter")
        .wrap(middleware::authentication)
        .route(
            "get_current",
            post().to(views::reader::place::chapter)
        )
        .route(
            "increment_current",
            post().to(views::reader::place::chapter)
        )
        .route(
            "decrement_current",
            post().to(views::reader::place::chapter)
        )
        .route(
            "set_new",
            post().to(views::reader::place::chapter)
        )
    )
}